### ISSUE TITLE
rosbag

### ISSUE THREAD

**Issue by dongfangzhou1108** [lastflowers/envio#1]
appreciate your great work！
can you release your rosbag in paper？
and have you test，can your method work in the condition of white wall？
thanks a lot！

**Comment by lastflowers** [comment]
Hi, thank you for your interest in our work!

Currently, I am not sure to release the flight dataset in the paper due to a license issue.
I expect that localizing in a pure white wall would be very challenging even for our method since our visual front-end depends on image gradients.

If you are interested, please check our snu301 sequences with a textureless wall in the readme file.

**Comment by dongfangzhou1108** [comment]
thanks a lot.
but when i try your snu301 rosbag, i find some wrong in your right camera like picture below.
best wishes!
![2022-02-10 19-12-27 的屏幕截图](https://user-images.githubusercontent.com/74195353/153396070-9c32df9f-7886-433c-bc60-69b243facfe7.png)

**Comment by arenas7307979** [comment]
There seems to be an error about "cam1 distortion_coeffs ",  I tried to fill in the same parameter as cam0 and it works fine, the correct value can wait for to update from author

**Comment by lastflowers** [comment]
I found that this is due to a different implementation of `cv::fisheye::estimateNewCameraMatrixForUndistortRectify` in opencv versions.

To resolve the issue, you should use the above function in OpenCV >= 3.4
https://github.com/opencv/opencv/blob/3.4/modules/calib3d/src/fisheye.cpp#L549

The new intrinsic matrix should be 

cv_Kl_new = [300.3127324163617, 0, 346.0204157455623;
 0, 299.9143972488393, 229.9477505201118;
 0, 0, 1]

cv_Kr_new = [300.290757544907, 0, 379.7844651209092;
 0, 300.1389715440906, 242.1087340715927;
 0, 0, 1]

Or you can just put this value to run the custom dataset.
